CREATE TABLE CUSTOMER(ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 1, increment by 1),FIRST_NAME VARCHAR(255),MIDDLE_NAME VARCHAR(255),LAST_NAME VARCHAR(255),PHONE VARCHAR(50),ADDRESS VARCHAR(255),EMAIL VARCHAR(100),STATUS VARCHAR(20),CREATED TIMESTAMP default CURRENT_TIMESTAMP)
CREATE TABLE NOTE(ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (start with 1, increment by 1),TEXT VARCHAR(255),CUSTOMER_ID BIGINT, FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID))
CREATE INDEX NOTE_CUSTOMER ON NOTE (CUSTOMER_ID)
